# Generated by Django 5.0.2 on 2024-02-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GovernmentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=100)),
                ("inwoners", models.CharField(max_length=20)),
                ("oppervlakte", models.CharField(max_length=20)),
                ("hoofdplaats", models.CharField(max_length=100)),
            ],
        ),
    ]
